#!/usr/bin/env bash
# Proves the SystemService/HAProxyService/NetworkService methods beyond
# the lifecycle ones on a real node: the full disk image under real OVMF
# with SELinux enforcing (baked into the UKI), every call made over mTLS
# with janusctl. Read-only methods first, then the disruptive ones in
# order - janusd restart (HAProxy must keep answering throughout), a
# reboot (PKI survives), a reset (PKI regenerated, old certificates
# refused), and a shutdown (QEMU exits). Fails on any AVC denial.
#
# Usage: hack/qemu-system-api-test.sh <disk.img> <janusctl-bin>
set -euo pipefail

export PATH="$PATH:/usr/sbin:/sbin"

DISK="${1:?usage: $0 <disk.img> <janusctl-bin>}"
CTL_BIN="${2:?usage: $0 <disk.img> <janusctl-bin>}"
BOOT_TIMEOUT_SECS="${QEMU_API_BOOT_TIMEOUT:-60}"
HOST_PORT_8080="${QEMU_API_TEST_PORT:-$((18200 + ${JANUS_TEST_PORT_OFFSET:-0}))}"
HOST_GRPC_PORT="${QEMU_API_GRPC_PORT:-$((18201 + ${JANUS_TEST_PORT_OFFSET:-0}))}"
HOST_PORT_8081="$((18202 + ${JANUS_TEST_PORT_OFFSET:-0}))"
HOST_PORT_8443="$((18203 + ${JANUS_TEST_PORT_OFFSET:-0}))"
MARKER="JANUS_INIT_BOOT_OK"
FIRST_BOOT_MSG="pki: first boot - generated a new CA"

OVMF_CODE="${OVMF_CODE:-/usr/share/OVMF/OVMF_CODE_4M.fd}"
OVMF_VARS_TEMPLATE="${OVMF_VARS_TEMPLATE:-/usr/share/OVMF/OVMF_VARS_4M.fd}"
[ -f "$OVMF_CODE" ] || { echo "OVMF firmware not found at $OVMF_CODE (package: ovmf)" >&2; exit 1; }

WORKDIR="$(mktemp -d)"
QEMU_PID=""
cleanup() {
  [ -n "$QEMU_PID" ] && kill "$QEMU_PID" 2>/dev/null || true
  rm -rf "$WORKDIR"
}
trap cleanup EXIT

LOG="$WORKDIR/boot.log"
fail() {
  echo "System API test FAILED: $*" >&2
  [ -f "$LOG" ] && { echo "--- console output ---" >&2; cat "$LOG" >&2; }
  exit 1
}

# No -no-reboot: Reboot and Reset must reboot the guest inside this same
# QEMU process, and Shutdown must make it exit.
cp "$OVMF_VARS_TEMPLATE" "$WORKDIR/OVMF_VARS.fd"
qemu-system-x86_64 -accel kvm -accel tcg \
  -drive if=pflash,format=raw,readonly=on,file="$OVMF_CODE" \
  -drive if=pflash,format=raw,file="$WORKDIR/OVMF_VARS.fd" \
  -drive file="$DISK",format=raw,if=virtio \
  -nographic -display none -m 512M \
  -netdev "user,id=net0,hostfwd=tcp::${HOST_PORT_8080}-:8080,hostfwd=tcp::${HOST_GRPC_PORT}-:9505,hostfwd=tcp::${HOST_PORT_8081}-:8081,hostfwd=tcp::${HOST_PORT_8443}-:8443" \
  -device virtio-net-pci,netdev=net0 \
  -serial file:"$LOG" \
  &
QEMU_PID=$!

http_code() { curl -s -m 2 -o /dev/null -w '%{http_code}' "http://127.0.0.1:${HOST_PORT_8080}/" || true; }
markers() { grep -ac "$MARKER" "$LOG" 2>/dev/null || true; }
wait_boot() { # wait_boot N: the Nth boot answers HTTP
  local deadline=$((SECONDS + BOOT_TIMEOUT_SECS))
  until [ "$(markers)" -ge "$1" ] && [ "$(http_code)" = "200" ]; do
    [ "$SECONDS" -lt "$deadline" ] || fail "boot #$1 never answered HTTP 200 within ${BOOT_TIMEOUT_SECS}s"
    sleep 1
  done
}
extract_pki() {
  local start size
  start="$(sgdisk -i 6 "$DISK" | awk -F': ' '/^First sector/ {print $2}' | awk '{print $1}')"
  size="$(sgdisk -i 6 "$DISK" | awk -F': ' '/^Partition size/ {print $2}' | awk '{print $1}')"
  dd if="$DISK" of="$WORKDIR/state.img" bs=512 skip="$start" count="$size" status=none
  for f in ca.crt admin.crt admin.key; do
    rm -f "$WORKDIR/$f"
    debugfs -R "dump pki/$f $WORKDIR/$f" "$WORKDIR/state.img" >/dev/null 2>&1
    [ -s "$WORKDIR/$f" ] || return 1
  done
}
ctl() { "$CTL_BIN" -endpoint "127.0.0.1:${HOST_GRPC_PORT}" -ca "$WORKDIR/ca.crt" -cert "$WORKDIR/admin.crt" -key "$WORKDIR/admin.key" "$@"; }
first_boots() { grep -ac "$FIRST_BOOT_MSG" "$LOG" 2>/dev/null || true; }
# HTTP 200 doesn't mean the API is up: janusd starts HAProxy before its
# PKI and its gRPC listener, and through QEMU's user network a port not
# listening yet looks like a TLS handshake ending in EOF.
wait_api() { # wait_api WHAT: janusd answers over mTLS with the current credentials
  local deadline=$((SECONDS + 60)) out
  until out="$(ctl version 2>&1)"; do
    [ "$SECONDS" -lt "$deadline" ] || fail "$1: janusd's API never answered (PKI generated $(first_boots) time(s) so far): $out"
    sleep 1
  done
}
wait_new_pki() { # wait_new_pki N: the PKI of the Nth first boot is on STATE and answers
  local deadline=$((SECONDS + 60))
  until [ "$(first_boots)" -ge "$1" ] && extract_pki && ctl version >/dev/null 2>&1; do
    [ "$SECONDS" -lt "$deadline" ] || fail "the PKI generated by first boot #$1 never answered over mTLS: $(ctl version 2>&1)"
    sleep 1
  done
}
expect() { # expect "description" "grep -E pattern" command...
  local what="$1" pattern="$2" out
  shift 2
  out="$("$@" 2>&1)" || fail "$what: janusctl $* failed: $out"
  echo "$out" | grep -Eq "$pattern" || fail "$what: output of janusctl $* doesn't match /$pattern/: $out"
  echo "  ok: $what"
}
haproxy_count() { ctl system ps | grep -c '/usr/local/sbin/haproxy -f' || true; }

wait_boot 1
wait_new_pki 1
echo "Boot 1 OK"

# --- read-only methods ---
expect "Hostname" '^[A-Za-z0-9.-]+$' ctl system hostname
expect "Stats lists janusd and haproxy" '^haproxy +[0-9.]+ ' ctl system stats
expect "SystemStat" '^processes created: [1-9]' ctl system systemstat
expect "Processes shows PID 1 (rootfs/init)" '^1 +[0-9.]+ +[0-9.]+[KM]iB +/sbin/init' ctl system ps
expect "NetworkDeviceStats counts eth0 traffic" '^eth0 +[0-9.]+[KM]iB' ctl system netdev
expect "Netstat sees the gRPC listener" '9505 +.* LISTEN' ctl system netstat
expect "Mounts shows the dm-verity root read-only" '^/dev/root \(squashfs\) +/ .* ro$' ctl system mounts
expect "Mounts shows STATE" '/dev/vda6 \(ext4\) +/etc/\.state ' ctl system mounts
expect "DiskUsage" '[0-9.]+(B|KiB)'$'\t''/etc/haproxy$' ctl system du /etc/haproxy
expect "List" 'haproxy\.cfg$' ctl system ls /etc/haproxy
expect "Read" '^frontend ' ctl system cat /etc/haproxy/haproxy.cfg
ctl system cp -o "$WORKDIR/etc-haproxy.tar" /etc/haproxy || fail "Copy failed"
tar tf "$WORKDIR/etc-haproxy.tar" | grep -qx 'haproxy/haproxy.cfg' || fail "Copy's tar doesn't hold haproxy/haproxy.cfg: $(tar tf "$WORKDIR/etc-haproxy.tar")"
echo "  ok: Copy (valid tar)"
if out="$(ctl system cat /dev/vda 2>&1)"; then fail "Read of a block device was allowed"; fi
echo "$out" | grep -q PermissionDenied || fail "Read(/dev/vda) didn't answer PermissionDenied: $out"
echo "  ok: Read refuses devices"
# The node's secrets are never served, however they're asked for: an
# admin certificate must not carry the CA's key away.
for p in /etc/janus/pki/ca.key /etc/.state/pki/admin.key /proc/self/root/etc/janus/pki/server.key; do
  if out="$(ctl system cat "$p" 2>&1)"; then fail "Read($p) was allowed"; fi
  grep -q PermissionDenied <<<"$out" || fail "Read($p) didn't answer PermissionDenied: $out"
done
if out="$(ctl system cp -o "$WORKDIR/pki.tar" /etc/janus/pki 2>&1)"; then fail "Copy(/etc/janus/pki) was allowed"; fi
grep -q PermissionDenied <<<"$out" || fail "Copy(/etc/janus/pki) didn't answer PermissionDenied: $out"
ctl system cp -o "$WORKDIR/etc-janus.tar" /etc/janus || fail "Copy(/etc/janus) failed"
listing="$(tar tf "$WORKDIR/etc-janus.tar")"
grep -q '^janus/network/' <<<"$listing" || fail "Copy(/etc/janus) lacks network/: $listing"
if grep -q '^janus/pki' <<<"$listing"; then fail "Copy(/etc/janus) holds the PKI: $listing"; fi
content="$(tar xOf "$WORKDIR/etc-janus.tar")"
if grep -q 'PRIVATE KEY' <<<"$content"; then fail "Copy(/etc/janus) holds a private key"; fi
echo "  ok: the PKI's keys are never served (Read, Copy, /proc/self/root)"

# A client certificate named after who it's for, valid for an hour - and
# a reader one: read-only methods, not the file API.
ctl pki generate-client-config -role os:reader -name ci-reader -ttl 1h "$WORKDIR/reader" >/dev/null || fail "generate-client-config -name -ttl failed"
subject="$(openssl x509 -in "$WORKDIR/reader/client.crt" -noout -subject)"
grep -Eq 'CN ?= ?ci-reader' <<<"$subject" || fail "the certificate isn't named ci-reader: $subject"
grep -Eq 'O ?= ?os:reader' <<<"$subject" || fail "the certificate isn't os:reader: $subject"
left=$(( $(date -d "$(openssl x509 -in "$WORKDIR/reader/client.crt" -noout -enddate | cut -d= -f2)" +%s) - $(date +%s) ))
[ "$left" -gt 3300 ] && [ "$left" -le 3600 ] || fail "the 1h certificate is valid for ${left}s more"
reader() { "$CTL_BIN" -endpoint "127.0.0.1:${HOST_GRPC_PORT}" -ca "$WORKDIR/reader/ca.crt" -cert "$WORKDIR/reader/client.crt" -key "$WORKDIR/reader/client.key" "$@"; }
expect "a reader certificate reads the hostname" '^[A-Za-z0-9.-]+$' reader system hostname
if out="$(reader system cat /etc/haproxy/haproxy.cfg 2>&1)"; then fail "a reader certificate read a file"; fi
grep -q PermissionDenied <<<"$out" || fail "Read with a reader certificate didn't answer PermissionDenied: $out"
echo "  ok: named, 1-hour reader certificate"
expect "Dmesg" 'Linux version' ctl system dmesg
expect "Logs janusd" 'listening on :9505' ctl system logs janusd
expect "Logs haproxy" 'NOTICE' ctl system logs haproxy
expect "ServiceList" '^haproxy +running +healthy' ctl system services
expect "BackendList" '^BACKEND' ctl haproxy backends
expect "NetworkService reports modules not in the image" 'bgp \(bird\): +not_enabled' ctl network modules

# A certificate uploaded at runtime: kept on STATE, it must be back in
# HAProxy after the reloads, the janusd restart and the reboot below.
openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:P-256 -nodes -days 30 \
  -subj "/CN=persist.example.test" -keyout "$WORKDIR/persist.key" -out "$WORKDIR/persist.crt" 2>/dev/null
cat "$WORKDIR/persist.crt" "$WORKDIR/persist.key" > "$WORKDIR/persist.pem"
ctl haproxy cert-upload persist-test.pem "$WORKDIR/persist.pem" >/dev/null || fail "cert-upload"
has_cert() { ctl haproxy cert-list 2>/dev/null | grep -q '^persist-test\.pem'; }
has_cert || fail "the uploaded certificate isn't listed: $(ctl haproxy cert-list 2>&1)"

# HAProxy's own files: an error page and a certificate haproxy.cfg uses,
# a private key never read back, changes that would break haproxy.cfg
# refused. They're on STATE: checked again after the reboot below.
openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:P-256 -nodes -days 30 \
  -subj "/CN=files.example.test" -keyout "$WORKDIR/files.key" -out "$WORKDIR/files.crt" 2>/dev/null
cat "$WORKDIR/files.crt" "$WORKDIR/files.key" > "$WORKDIR/files.pem"
printf 'HTTP/1.0 503 Service Unavailable\r\nContent-Type: text/plain\r\n\r\njanus-files-test-503\n' > "$WORKDIR/503.http"
ctl haproxy file-put errors/503.http "$WORKDIR/503.http" >/dev/null || fail "file-put the error page"
ctl haproxy file-put certs/files.pem "$WORKDIR/files.pem" >/dev/null || fail "file-put the certificate"
expect "FileList" '^certs/files\.pem .*private key' ctl haproxy files
expect "FileGet" 'janus-files-test-503' ctl haproxy file-get errors/503.http
if ctl haproxy file-get certs/files.pem >/dev/null 2>&1; then fail "a private key was read back"; fi
# log stdout, as a configuration brought from a distribution uses: HAProxy
# checks whether it's a terminal - a denial a real node hit.
ctl haproxy get-config | awk '{print} /^global/{print "    log stdout format raw local0"}' > "$WORKDIR/files.cfg"
cat >> "$WORKDIR/files.cfg" <<'EOF2'

frontend files-test
    bind *:8081
    bind *:8443 ssl crt /etc/haproxy/files/certs/files.pem
    log global
    option httplog
    default_backend files-none

backend files-none
    errorfile 503 /etc/haproxy/files/errors/503.http
EOF2
ctl haproxy apply-config "$WORKDIR/files.cfg" >/dev/null || fail "a haproxy.cfg using the files was refused"
files_served() {
  curl -s -m 3 "http://127.0.0.1:${HOST_PORT_8081}/" | grep -q janus-files-test-503 &&
    openssl s_client -connect "127.0.0.1:${HOST_PORT_8443}" -servername files.example.test </dev/null 2>/dev/null |
    openssl x509 -noout -subject | grep -q files.example.test
}
files_served || fail "the error page or the certificate from the files isn't served"
# The global section a node requires (internal/haproxy.GlobalPolicy):
# without the privilege drop, with a second stats socket on the network
# or with daemon, the configuration is refused before haproxy -c, and
# the running one stays.
grep -v '^    uid 1000$' "$WORKDIR/files.cfg" > "$WORKDIR/no-uid.cfg"
if out="$(ctl haproxy apply-config "$WORKDIR/no-uid.cfg" 2>&1)"; then fail "a configuration without uid 1000 was applied"; fi
grep -q '"uid 1000" is required' <<<"$out" || fail "the refusal doesn't name uid 1000: $out"
awk '{print} /^global/{print "    stats socket ipv4@0.0.0.0:9999 level admin"}' "$WORKDIR/files.cfg" > "$WORKDIR/net-socket.cfg"
if out="$(ctl haproxy apply-config "$WORKDIR/net-socket.cfg" 2>&1)"; then fail "a stats socket on the network was applied"; fi
grep -q "only janusd's socket" <<<"$out" || fail "the refusal doesn't name the socket: $out"
awk '{print} /^global/{print "    daemon"}' "$WORKDIR/files.cfg" > "$WORKDIR/daemon.cfg"
if out="$(ctl haproxy apply-config "$WORKDIR/daemon.cfg" 2>&1)"; then fail "daemon was applied"; fi
grep -q '"daemon" isn.t allowed' <<<"$out" || fail "the refusal doesn't name daemon: $out"
files_served || fail "the files aren't served any more after the refused configurations"
echo "  ok: the global section a node requires (uid, janusd's only stats socket, no daemon)"
ctl system logs -n 500 haproxy | grep -q "files-test" || fail "HAProxy's access log (log stdout) isn't in its service log"
if ctl haproxy file-delete errors/503.http >/dev/null 2>&1; then fail "an error page in use was removed"; fi
echo garbage > "$WORKDIR/garbage.pem"
if ctl haproxy file-put -reload certs/files.pem "$WORKDIR/garbage.pem" >/dev/null 2>&1; then fail "a broken certificate was accepted"; fi
ctl system service restart haproxy >/dev/null || fail "reload after a refused change"
sleep 2
files_served || fail "the files aren't served any more after a refused change and a reload"
echo "  ok: HAProxy files (error page and certificate served, private key never read back, breaking changes refused; access log through log stdout)"

# --- open files: what a distribution gives HAProxy (rootfs/init raises the
# hard limit to systemd's); a configuration haproxy -c accepts but HAProxy
# won't start with is refused, nothing changed ---
expect "HAProxy sized from the node's open-files limit" 'Connections: +[0-9]+ / 26[0-9]{4}$' ctl haproxy show-info
awk '{print} /^global/{print "    ulimit-n 524288"}' "$WORKDIR/files.cfg" > "$WORKDIR/ulimit.cfg"
ctl haproxy apply-config "$WORKDIR/ulimit.cfg" >/dev/null || fail "ulimit-n 524288 (systemd's limit for a service) was refused"
awk '{print} /^global/{print "    ulimit-n 2000000000"}' "$WORKDIR/files.cfg" > "$WORKDIR/impossible.cfg"
if out="$(ctl haproxy apply-config "$WORKDIR/impossible.cfg" 2>&1)"; then fail "a configuration HAProxy can't start with was reported applied: $out"; fi
grep -q "FD limit" <<<"$out" || fail "the refusal doesn't give HAProxy's reason: $out"
ctl haproxy get-config | cmp -s - "$WORKDIR/ulimit.cfg" || fail "the refused configuration replaced the previous one"
files_served || fail "HAProxy stopped serving after a refused start"
[ "$(haproxy_count)" = 1 ] || fail "$(haproxy_count) haproxy processes after a refused start"
echo "  ok: open files (ulimit-n 524288 accepted, an impossible one refused with HAProxy's reason, previous configuration kept)"

# --- service control ---
ctl system service restart haproxy >/dev/null || fail "ServiceRestart haproxy failed"
sleep 2
[ "$(haproxy_count)" -eq 1 ] || fail "after a seamless restart, $(haproxy_count) haproxy processes are running, want 1: $(ctl system ps)"
[ "$(http_code)" = "200" ] || fail "HTTP down after ServiceRestart haproxy"
has_cert || fail "the uploaded certificate is gone after a reload: $(ctl haproxy cert-list 2>&1)"
echo "  ok: ServiceRestart haproxy (seamless, old process gone, uploaded certificate kept)"
ctl system service stop haproxy >/dev/null || fail "ServiceStop haproxy failed"
[ "$(http_code)" != "200" ] || fail "HTTP still answering after ServiceStop haproxy"
ctl system service start haproxy >/dev/null || fail "ServiceStart haproxy failed"
sleep 1
[ "$(http_code)" = "200" ] || fail "HTTP not back after ServiceStart haproxy"
echo "  ok: ServiceStop / ServiceStart haproxy"
timeout 3 "$CTL_BIN" -endpoint "127.0.0.1:${HOST_GRPC_PORT}" -ca "$WORKDIR/ca.crt" -cert "$WORKDIR/admin.crt" -key "$WORKDIR/admin.key" system events > "$WORKDIR/events.txt" || true
for ev in janusd.started haproxy.started service.stopped service.started 'haproxy.exited.*replaced by a reload'; do
  grep -Eq "$ev" "$WORKDIR/events.txt" || fail "Events has no '$ev': $(cat "$WORKDIR/events.txt")"
done
echo "  ok: Events"

# --- Restart: janusd only, HAProxy must keep answering throughout ---
old_haproxy="$(ctl system ps | awk '/\/usr\/local\/sbin\/haproxy -f/ {print $1}')"
ctl system restart >/dev/null || fail "Restart failed"
drops=0
for _ in $(seq 1 20); do
  [ "$(http_code)" = "200" ] || drops=$((drops + 1))
  sleep 0.5
done
[ "$drops" -eq 0 ] || fail "HTTP failed $drops times while janusd restarted"
deadline=$((SECONDS + 30))
until ctl version >/dev/null 2>&1; do
  [ "$SECONDS" -lt "$deadline" ] || fail "janusd didn't come back after Restart"
  sleep 1
done
sleep 2
ctl system ps | grep -q "/usr/local/sbin/haproxy -f /etc/haproxy/haproxy.cfg -sf $old_haproxy" || fail "the restarted janusd didn't take over haproxy $old_haproxy with -sf: $(ctl system ps)"
[ "$(haproxy_count)" -eq 1 ] || fail "$(haproxy_count) haproxy processes after the janusd restart, want 1: $(ctl system ps)"
[ "$(markers)" -eq 1 ] || fail "the machine rebooted during a janusd-only Restart"
echo "  ok: Restart (HAProxy served every request, new janusd took haproxy over)"

# --- Reboot: PKI survives ---
ctl system reboot >/dev/null || fail "Reboot failed"
wait_boot 2
wait_api "after Reboot"
[ "$(first_boots)" -eq 1 ] || fail "PKI was regenerated by a plain Reboot"
expect "same credentials after Reboot" '^Node:' ctl version
has_cert || fail "the uploaded certificate is gone after the reboot: $(ctl haproxy cert-list 2>&1)"
files_served || fail "HAProxy's files aren't served after the reboot"
echo "  ok: Reboot (same credentials, uploaded certificate back in HAProxy, its files kept)"

# --- Reset: STATE wiped, new PKI, old certificates refused ---
ctl system reset -wipe-state >/dev/null || fail "Reset failed"
wait_boot 3
mkdir -p "$WORKDIR/old"
cp "$WORKDIR/ca.crt" "$WORKDIR/admin.crt" "$WORKDIR/admin.key" "$WORKDIR/old/"
wait_new_pki 2
# Only now that the API answers is a refusal of the old credentials
# meaningful.
if "$CTL_BIN" -endpoint "127.0.0.1:${HOST_GRPC_PORT}" -ca "$WORKDIR/old/ca.crt" -cert "$WORKDIR/old/admin.crt" -key "$WORKDIR/old/admin.key" version >/dev/null 2>&1; then
  fail "the pre-reset admin certificate still works after Reset"
fi
expect "new credentials after Reset" '^Node:' ctl version
echo "  ok: Reset"

# --- Shutdown: QEMU exits ---
ctl system shutdown >/dev/null || fail "Shutdown failed"
deadline=$((SECONDS + 30))
while kill -0 "$QEMU_PID" 2>/dev/null; do
  [ "$SECONDS" -lt "$deadline" ] || fail "the VM didn't power off after Shutdown"
  sleep 1
done
QEMU_PID=""
echo "  ok: Shutdown (VM powered off)"

if grep -a "avc:.*denied" "$LOG"; then
  fail "SELinux denials"
fi
echo "System API test OK: every method exercised on a real enforcing node over mTLS, zero AVC denials"
