// Command dashboardd is the management dashboard's backend - see the
// rebranding/dashboard/client-native plan for the full architecture.
// Serves the SPA + a REST/JSON API for managing the node registry on one
// HTTPS-only port (behind a single admin password - see internal/auth -
// forced setup on first run, session-cookie-gated after that; the
// session cookie is marked Secure, so this transport guarantee actually
// matters, not just cosmetic), and one dedicated HTTPS listener per
// registered node (see dashboard/backend/internal/nodeproxy) requiring a
// TLS client certificate signed by that node's own CA - a browser
// already holding a valid client cert for that node gets prompted to
// select it the first time it connects to that node's own port.
//
// Every TLS surface this process serves (the main UI, node self-
// registration, and every per-node listener) shares one identity
// certificate - see loadOrCreateDashboardIdentity: self-signed and
// auto-generated on first run by default (persisted to -data-dir, so
// it's stable across restarts - a fresh one every restart would mean a
// new browser trust warning every time for no reason), or -tls-cert/
// -tls-key to supply a real one instead (e.g. a Let's Encrypt
// certificate, or an internal CA's). Either way it's self-signed or
// otherwise not in a browser's default trust store, so a first visit to
// the main UI needs the same one-time click-through a per-node view
// already needed.
package main

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"embed"
	"encoding/json"
	"encoding/pem"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"log"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	pkcs12 "software.sslmate.com/src/go-pkcs12"

	janusv1alpha1 "github.com/swenske/Janus/gen/janus/v1alpha1"
	"github.com/swenske/Janus/internal/pki"

	"github.com/swenske/Janus/dashboard/backend/internal/audit"
	"github.com/swenske/Janus/dashboard/backend/internal/auth"
	"github.com/swenske/Janus/dashboard/backend/internal/backup"
	"github.com/swenske/Janus/dashboard/backend/internal/enroll"
	"github.com/swenske/Janus/dashboard/backend/internal/fleet"
	"github.com/swenske/Janus/dashboard/backend/internal/hypervisor"
	"github.com/swenske/Janus/dashboard/backend/internal/labels"
	"github.com/swenske/Janus/dashboard/backend/internal/machines"
	"github.com/swenske/Janus/dashboard/backend/internal/nodeproxy"
	"github.com/swenske/Janus/dashboard/backend/internal/pending"
	"github.com/swenske/Janus/dashboard/backend/internal/secrets"
	"github.com/swenske/Janus/dashboard/backend/internal/store"
	"github.com/swenske/Janus/dashboard/updater/updaterapi"
)

// staticFiles is dashboard/frontend's built React SPA - dashboard/
// backend/static, generated by `make dashboard-frontend-build`
// (dashboard/frontend's own `npm run build`, configured to output
// straight here - see vite.config.js). Committed to the repo the same
// way gen/janus/v1alpha1 is: never hand-edited, but committed
// anyway so a plain `go build ./...` never needs a Node.js toolchain
// just to compile - go:embed needs real files present at build time,
// not just at dashboard-image-build time.
//
//go:embed all:static
var staticFiles embed.FS

// version is set at build time (-X main.version, the Makefile and
// dashboard/Dockerfile).
var version = "dev"

func main() {
	if len(os.Args) > 1 && os.Args[1] == "reset-user" {
		resetUser(os.Args[2:])
		return
	}
	if len(os.Args) > 1 && os.Args[1] == "restore" {
		restoreCommand(os.Args[2:])
		return
	}
	addr := flag.String("addr", envOr("JANUS_CONTROLLER_ADDR", ":8080"), "main HTTPS address (node list, add/remove - never a credential) - e.g. \":443\" to run the UI on the standard HTTPS port; also settable via JANUS_CONTROLLER_ADDR (same \":port\"/\"host:port\" format - a flag takes precedence over the env var if both are given), for Docker Compose deployments where an environment: entry is more natural than overriding the container's command")
	registerAddr := flag.String("register-addr", ":8443", "TLS address nodes self-register against (see internal/pending) - not the same port pool as approved nodes' own per-node listeners")
	dataDir := flag.String("data-dir", "/data", "persistent data directory (Docker volume) - node registry + this dashboard's own TLS identity")
	advertiseAddresses := flag.String("advertise-address", envOr("JANUS_CONTROLLER_ADVERTISE_ADDRESS", ""), "comma-separated extra IPs/hostnames to add to this dashboard's TLS identity certificate, alongside loopback and this host's own local IPs (see loadOrCreateDashboardIdentity) - needed whenever a node or browser reaches -addr/-register-addr/the per-node ports through an address this process can't see on its own network interfaces (Docker bridge networking's host-side published port, a NAT/port-forwarded address, ...); only used the first time the identity is generated (or ignored entirely if -tls-cert/-tls-key are set), since it's cached to -data-dir afterward - delete <data-dir>/dashboard-identity.{crt,key} to regenerate after changing this; also settable via JANUS_CONTROLLER_ADVERTISE_ADDRESS, same reasoning as JANUS_CONTROLLER_ADDR above")
	tlsCertFile := flag.String("tls-cert", "", "path to a PEM certificate for this dashboard's own TLS identity (used for -addr, -register-addr, and every per-node listener) - if set, together with -tls-key, replaces the auto-generated self-signed one entirely; both flags must be set together")
	masterKeyFile := flag.String("master-key-file", envOr("JANUS_CONTROLLER_MASTER_KEY_FILE", ""), "the master key sealing the fleet's issuing CA key (internal/secrets), made there the first time - keep it outside -data-dir so a copy of the data holds nothing usable; empty: <data-dir>/master.key, which the Controller warns about; also settable via JANUS_CONTROLLER_MASTER_KEY_FILE")
	tlsKeyFile := flag.String("tls-key", "", "path to the PEM private key matching -tls-cert")
	imageFactory := flag.String("image-factory", envOr("JANUS_CONTROLLER_IMAGE_FACTORY", nodeproxy.ImageFactoryURL), "image factory that builds and serves the updates of nodes whose image has optional extensions (docs/image-factory.md) - empty to disable, in which case such nodes have no update source; nodes with the default schematic update from GitHub Releases either way; also settable via JANUS_CONTROLLER_IMAGE_FACTORY")
	updaterSocket := flag.String("updater-socket", envOr("JANUS_CONTROLLER_UPDATER_SOCKET", updaterapi.DefaultSocket), "Unix socket of janus-controller-updater, which updates this Controller when asked from its page (dashboard/README.md, Updating the Controller) - nothing happens when it isn't there; empty to never use one; also settable via JANUS_CONTROLLER_UPDATER_SOCKET")
	releasesURL := flag.String("releases-url", envOr("JANUS_CONTROLLER_RELEASES_URL", nodeproxy.ReleasesURL), "GitHub API URL listing Janus releases, newest first - where the Controller learns about new releases for itself and its nodes (a mirror, or a test's fake); also settable via JANUS_CONTROLLER_RELEASES_URL")
	flag.Parse()
	nodeproxy.ImageFactoryURL = *imageFactory
	nodeproxy.ReleasesURL = *releasesURL
	nodeproxy.ControllerVersion = version

	st, err := store.Open(*dataDir)
	if err != nil {
		log.Fatalf("open store: %v", err)
	}

	pendingStore, err := pending.Open(*dataDir)
	if err != nil {
		log.Fatalf("open pending store: %v", err)
	}

	authStore, err := auth.Open(*dataDir)
	if err != nil {
		log.Fatalf("open auth store: %v", err)
	}
	tokenStore, err := auth.OpenTokens(*dataDir)
	if err != nil {
		log.Fatalf("open API token store: %v", err)
	}
	if authStore.SetupRequired() {
		log.Printf("no account yet - the UI will force a one-time setup screen on first visit")
	}
	auditLog, err := audit.Open(*dataDir)
	if err != nil {
		log.Fatalf("open the audit: %v", err)
	}

	serverCert, err := loadOrCreateDashboardIdentity(*dataDir, *advertiseAddresses, *tlsCertFile, *tlsKeyFile)
	if err != nil {
		log.Fatalf("dashboard TLS identity: %v", err)
	}

	controllerID, err := loadOrCreateControllerID(*dataDir)
	if err != nil {
		log.Fatalf("controller ID: %v", err)
	}
	hypervisorStore, err := hypervisor.Open(*dataDir)
	if err != nil {
		log.Fatalf("open hypervisor store: %v", err)
	}
	enrollStore, err := enroll.Open(*dataDir)
	if err != nil {
		log.Fatalf("open the enrollment tokens: %v", err)
	}
	machineStore, err := machines.Open(*dataDir)
	if err != nil {
		log.Fatalf("open machine store: %v", err)
	}
	masterKey, err := secrets.LoadOrCreate(*masterKeyFile, *dataDir)
	if err != nil {
		log.Fatalf("master key: %v", err)
	}
	if masterKey.BesideData {
		log.Printf("WARNING: the master key is %s, in the data directory: a copy of it holds the fleet's issuing CA key and the accounts' authenticator secrets - set JANUS_CONTROLLER_MASTER_KEY_FILE to a file outside it (dashboard/README.md)", masterKey.Path)
	}
	authStore.SetSealer(masterKey)
	backupStore, err := backup.OpenStore(filepath.Join(*dataDir, "backup"), masterKey, controllerID)
	if err != nil {
		log.Fatalf("open the backups: %v", err)
	}
	fleetStore, err := fleet.Open(filepath.Join(*dataDir, "fleet"), masterKey, controllerID)
	if err != nil {
		log.Fatalf("open the fleet: %v", err)
	}
	nodeproxy.FleetIdentity = fleetStore.ClientCertificate
	nodeproxy.NodeCA = func(n *store.Node, caPEM []byte) error { return st.SetCA(n.ID, caPEM) }

	app := &app{
		store:                 st,
		pending:               pendingStore,
		auth:                  authStore,
		tokens:                tokenStore,
		loginLimiter:          auth.NewLoginLimiter(),
		audit:                 auditLog,
		backups:               backupStore,
		masterKeyPath:         masterKey.Path,
		serverCert:            serverCert,
		suggestedRegisterAddr: suggestRegisterAddress(*advertiseAddresses, *registerAddr),
		selfUpdate:            newSelfUpdate(*updaterSocket),
		dataDir:               *dataDir,
		controllerID:          controllerID,
		hypervisors:           hypervisorStore,
		machines:              machineStore,
		enroll:                enrollStore,
		fleet:                 fleetStore,
		trust:                 newTrustTracker(),
	}
	app.runner = newMachineRunner(app)
	if err := app.startRegistrationListener(*registerAddr); err != nil {
		log.Fatalf("registration listener: %v", err)
	}
	app.runner.resume()
	go app.runner.syncLoop(context.Background())
	go app.trustLoop(context.Background())
	go app.backupLoop(context.Background())
	// The node pages: a machine's lock, and its record read again after a
	// change made there.
	nodeproxy.LockedBy = func(n *store.Node) string {
		if m, ok := app.machines.Get(n.MachineID); ok && n.MachineID != "" && m.Spec.Locked {
			return or(m.Spec.ManagedBy, "code")
		}
		return ""
	}
	nodeproxy.NodeChanged = app.runner.syncNode

	spa, err := fs.Sub(staticFiles, "static")
	if err != nil {
		log.Fatalf("static assets: %v", err)
	}

	srv := &http.Server{
		Addr: *addr,
		// The session cookie's SameSite=Strict already keeps it off
		// cross-site requests, but not off same-site ones (another port
		// or subdomain of the same host) - refuse any non-safe request
		// from another origin outright, the same protection every
		// per-node listener has (see nodeproxy.newHandler).
		Handler:   app.unlessRestored(http.NewCrossOriginProtection().Handler(app.audited(app.routes(spa)))),
		TLSConfig: &tls.Config{Certificates: []tls.Certificate{serverCert}},
	}
	ln, err := net.Listen("tcp", *addr)
	if err != nil {
		log.Fatalf("listen on %s: %v", *addr, err)
	}
	log.Printf("dashboardd %s listening on %s (HTTPS only)", version, *addr)
	// Listening now: an update waiting for this version to start can stop
	// waiting.
	go app.selfUpdate.announce()
	// Empty cert/key file arguments: srv.TLSConfig.Certificates above is
	// what's actually used - ServeTLS falls back to it exactly for this
	// case (see its own doc comment).
	log.Fatal(srv.ServeTLS(ln, "", ""))
}

// routes is the main port's API and the page: every API route behind a
// gate naming the role a read and a change of it need.
func (a *app) routes(spa fs.FS) *http.ServeMux {
	mux := http.NewServeMux()
	mux.HandleFunc("/api/auth/status", a.handleAuthStatus)
	mux.HandleFunc("POST /api/auth/setup", a.handleAuthSetup)
	mux.HandleFunc("POST /api/auth/login", a.handleAuthLogin)
	mux.HandleFunc("POST /api/auth/logout", a.handleAuthLogout)
	mux.HandleFunc("POST /api/auth/password", a.handleAuthPassword)
	a.registerMFARoutes(mux)
	// The nodes an account reaches - its role over everything, or its
	// grants' labels (access.go); adding, removing and labelling them is
	// an admin's.
	mux.HandleFunc("/api/nodes", a.gate(anyone, auth.Admin, a.handleNodes))
	mux.HandleFunc("GET /api/nodes/status", a.gate(anyone, anyone, a.handleNodesStatus))
	mux.HandleFunc("GET /api/version", a.gate(anyone, anyone, func(w http.ResponseWriter, _ *http.Request) {
		writeJSON(w, http.StatusOK, map[string]string{"version": version})
	}))
	mux.HandleFunc("/api/nodes/", a.gate(auth.Reader, auth.Admin, a.handleNode))
	mux.HandleFunc("/api/pending", a.gate(anyone, auth.Admin, a.handlePendingList)) // none for an account without a role over everything
	mux.HandleFunc("/api/pending/", a.gate(auth.Reader, auth.Admin, a.handlePendingAction))
	mux.HandleFunc("/api/controller-info", a.gate(auth.Reader, auth.Admin, a.handleControllerInfo))
	mux.HandleFunc("/api/controller/update", a.gate(auth.Reader, auth.Admin, a.handleControllerUpdate))
	mux.HandleFunc("/nodes/", a.handleNodePage)
	a.registerTokenRoutes(mux)
	a.registerEnrollRoutes(mux)
	a.registerUserRoutes(mux)
	a.registerCLIRoutes(mux)
	a.registerSSHKeyRoutes(mux)
	a.registerCLIBrowserRoutes(mux)
	a.registerBackupRoutes(mux)
	a.registerRestoreRoutes(mux)
	a.registerHypervisorRoutes(mux)
	a.registerFleetRoutes(mux)
	a.registerMachineRoutes(mux)
	mux.Handle("/", http.FileServerFS(spa))
	return mux
}

type app struct {
	store        *store.Store
	pending      *pending.Store
	auth         *auth.Store
	tokens       *auth.TokenStore
	loginLimiter *auth.LoginLimiter
	audit        *audit.Log
	backups      *backup.Store
	// masterKeyPath is the master key's file - a backup takes it.
	masterKeyPath string
	serverCert    tls.Certificate
	// suggestedRegisterAddr is handleControllerInfo's best guess at the
	// address a node should be given as -controller-address at
	// provisioning time - see suggestRegisterAddress's own doc comment.
	// Empty when nothing suitable could be determined; the UI/operator
	// still has to confirm or override it for their actual network
	// either way, this is a convenience default, never authoritative.
	suggestedRegisterAddr string
	selfUpdate            *selfUpdate

	dataDir string
	// controllerID tags every virtual machine this Controller creates
	// (loadOrCreateControllerID).
	controllerID string
	hypervisors  *hypervisor.Store
	machines     *machines.Store
	// enroll: enrollment tokens - a batch of nodes admitted on one.
	enroll   *enroll.Store
	fleet    *fleet.Store
	trust    *trustTracker
	runner   *machineRunner
	consoles consoleHub

	challenges challenges
	// restored: a backup was restored - the process starts again.
	restored  atomic.Bool
	cliLogins cliLogins
	// pages holds each node's page handler (node_pages.go), made on its
	// first request.
	pagesMu sync.Mutex
	pages   map[string]http.Handler
	// createMu serializes machine creations' checks (a unique name) with
	// their records.
	createMu sync.Mutex
	hvStatus statusCache
}

// addNodeRequest is the JSON form of "add a node": three raw PEM blocks
// pasted in directly. Superseded in the frontend by a .pfx upload (see
// parseAddNodeRequest below) - copying three separate PEM blocks by
// hand turned out to be real friction for one single one-time event,
// the same lesson cmd/janusd/main.go's own bootstrap print already
// learned (see its own comment on why the CA cert prints alongside the
// admin cert/key rather than being split across two recovery paths).
// Kept working, not just left for compatibility: hack/
// qemu-dashboard-test.sh drives this JSON path directly, and a script/
// CI caller with raw PEM files in hand (e.g. straight out of
// janusctl pki generate-client-config) has no reason to wrap them
// in a PKCS#12 file first just to satisfy the UI's preferred format.
type addNodeRequest struct {
	Name             string `json:"name"`
	Address          string `json:"address"`
	CACertPEM        string `json:"ca_cert_pem"`
	BootstrapCertPEM string `json:"bootstrap_cert_pem"`
	BootstrapKeyPEM  string `json:"bootstrap_key_pem"`
}

// parseAddNodeRequest reads name/address/CA-cert/bootstrap-cert/
// bootstrap-key from either a multipart/form-data upload (fields
// "name", "address", "pfx" file, "pfx_password" - the default the
// frontend now uses: a single .pfx file, no PEM text to paste at all)
// or the older addNodeRequest JSON body, dispatched on Content-Type.
// Both arrive at exactly the same three PEM blocks handleAddNode
// already knew what to do with - this function's only job is getting
// there from either shape.
func parseAddNodeRequest(r *http.Request) (name, address string, caPEM, certPEM, keyPEM []byte, err error) {
	if strings.HasPrefix(r.Header.Get("Content-Type"), "multipart/form-data") {
		// 1 MiB is generous for a .pfx holding one EC key + two small
		// certs (a few KB in practice) - just a sanity cap, not a real
		// constraint.
		if err := r.ParseMultipartForm(1 << 20); err != nil {
			return "", "", nil, nil, nil, fmt.Errorf("parse form: %w", err)
		}
		name = r.FormValue("name")
		address = r.FormValue("address")
		password := r.FormValue("pfx_password")

		file, _, ferr := r.FormFile("pfx")
		if ferr != nil {
			return "", "", nil, nil, nil, fmt.Errorf("read pfx upload: %w", ferr)
		}
		defer file.Close()
		pfxData, rerr := io.ReadAll(file)
		if rerr != nil {
			return "", "", nil, nil, nil, fmt.Errorf("read pfx upload: %w", rerr)
		}

		key, cert, caCerts, derr := pkcs12.DecodeChain(pfxData, password)
		if derr != nil {
			return "", "", nil, nil, nil, fmt.Errorf("decode pfx (wrong password?): %w", derr)
		}
		if len(caCerts) == 0 {
			return "", "", nil, nil, nil, fmt.Errorf("pfx has no CA certificate bundled - it needs to include the node's ca.crt (e.g. openssl pkcs12 -export -certfile ca.crt ...)")
		}
		keyDER, merr := x509.MarshalPKCS8PrivateKey(key)
		if merr != nil {
			return "", "", nil, nil, nil, fmt.Errorf("marshal private key from pfx: %w", merr)
		}
		certPEM = pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: cert.Raw})
		keyPEM = pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: keyDER})
		caPEM = pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: caCerts[0].Raw})
		return name, address, caPEM, certPEM, keyPEM, nil
	}

	var req addNodeRequest
	if derr := json.NewDecoder(r.Body).Decode(&req); derr != nil {
		return "", "", nil, nil, nil, fmt.Errorf("decode request: %w", derr)
	}
	return req.Name, req.Address, []byte(req.CACertPEM), []byte(req.BootstrapCertPEM), []byte(req.BootstrapKeyPEM), nil
}

func (a *app) handleNodes(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		out := []nodeView{}
		for _, n := range a.visibleNodes(requestPrincipal(r)) {
			out = append(out, viewNode(n))
		}
		writeJSON(w, http.StatusOK, out)

	case http.MethodPost:
		a.handleAddNode(w, r)

	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

func (a *app) handleAddNode(w http.ResponseWriter, r *http.Request) {
	name, address, caPEM, bootstrapCertPEM, bootstrapKeyPEM, err := parseAddNodeRequest(r)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if name == "" || address == "" {
		http.Error(w, "name and address are required", http.StatusBadRequest)
		return
	}

	tlsConfig, err := pki.ClientTLSConfig(caPEM, bootstrapCertPEM, bootstrapKeyPEM)
	if err != nil {
		http.Error(w, fmt.Sprintf("build TLS config from provided credentials: %v", err), http.StatusBadRequest)
		return
	}
	conn, err := grpc.NewClient(address, grpc.WithTransportCredentials(credentials.NewTLS(tlsConfig)))
	if err != nil {
		http.Error(w, fmt.Sprintf("dial %s: %v", address, err), http.StatusBadGateway)
		return
	}
	defer conn.Close()

	ctx, cancel := context.WithTimeout(r.Context(), 10*time.Second)
	defer cancel()
	cfg, err := janusv1alpha1.NewSystemServiceClient(conn).GenerateClientConfiguration(ctx, &janusv1alpha1.GenerateClientConfigurationRequest{
		Roles: []string{pki.RoleAdmin},
		Name:  "janus-controller", // a node older than names says "client"
	})
	if err != nil {
		http.Error(w, fmt.Sprintf("GenerateClientConfiguration against %s: %v - the provided bootstrap credential couldn't reach or authenticate to that node", address, err), http.StatusBadGateway)
		return
	}
	// bootstrapCertPEM/bootstrapKeyPEM are never referenced again past
	// this point - only cfg's freshly-issued service credential is
	// persisted below.

	node := &store.Node{
		Name:           name,
		Address:        address,
		CACertPEM:      cfg.GetCa(),
		ServiceCertPEM: cfg.GetCrt(),
		ServiceKeyPEM:  cfg.GetKey(),
	}
	if err := a.store.Add(node); err != nil {
		http.Error(w, fmt.Sprintf("persist node: %v", err), http.StatusInternalServerError)
		return
	}
	a.trust.Kick() // brought to trust the fleet at once

	writeJSON(w, http.StatusCreated, struct {
		ID string `json:"id"`
	}{ID: node.ID})
}

type nodeView struct {
	ID        string            `json:"id"`
	Name      string            `json:"name"`
	Address   string            `json:"address"`
	MachineID string            `json:"machine_id,omitempty"`
	Labels    map[string]string `json:"labels"`
}

func viewNode(n *store.Node) nodeView {
	l := n.LabelSet()
	if l == nil {
		l = map[string]string{}
	}
	return nodeView{ID: n.ID, Name: n.Name, Address: n.Addr(), MachineID: n.MachineID, Labels: l}
}

func (a *app) handleNode(w http.ResponseWriter, r *http.Request) {
	id := r.URL.Path[len("/api/nodes/"):]
	if id == "" {
		http.Error(w, "missing node id", http.StatusBadRequest)
		return
	}
	if r.Method == http.MethodPatch {
		// PATCH {"labels": {...}}: the node's labels, replaced.
		var req struct {
			Labels map[string]string `json:"labels"`
		}
		if !decodeBody(w, r, &req) {
			return
		}
		if err := labels.Check(req.Labels); err != nil {
			writeError(w, http.StatusBadRequest, err.Error())
			return
		}
		n, ok := a.store.Get(id)
		if !ok {
			writeError(w, http.StatusNotFound, "no such node")
			return
		}
		if err := a.store.SetLabels(id, req.Labels); err != nil {
			writeError(w, http.StatusInternalServerError, err.Error())
			return
		}
		writeJSON(w, http.StatusOK, viewNode(n))
		return
	}
	if r.Method != http.MethodDelete {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	// Removing the node alone would leave its virtual machine running,
	// owned by nobody: it goes with its machine (DELETE /api/machines).
	if n, ok := a.store.Get(id); ok && n.MachineID != "" {
		if _, ok := a.machines.Get(n.MachineID); ok {
			http.Error(w, "this node runs in a virtual machine the Controller created: destroy the machine instead", http.StatusConflict)
			return
		}
	}

	if err := a.removeNode(r.Context(), id); err != nil {
		http.Error(w, err.Error(), http.StatusNotFound)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// handleNodesStatus reports every registered node's live status, queried
// concurrently with a short timeout so one unreachable node can't stall
// the node list.
func (a *app) handleNodesStatus(w http.ResponseWriter, r *http.Request) {
	nodes := a.visibleNodes(requestPrincipal(r))
	out := make(map[string]nodeproxy.NodeStatus, len(nodes))
	var mu sync.Mutex
	var wg sync.WaitGroup
	for _, n := range nodes {
		wg.Add(1)
		go func() {
			defer wg.Done()
			ctx, cancel := context.WithTimeout(r.Context(), 4*time.Second)
			defer cancel()
			st := nodeproxy.Status(ctx, n)
			mu.Lock()
			out[n.ID] = st
			mu.Unlock()
		}()
	}
	wg.Wait()
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(out)
}

// loadOrCreateDashboardIdentity gives every TLS surface this process
// serves (the main UI, node self-registration, and every per-node
// listener) one stable server certificate across restarts (a fresh
// self-signed identity every restart would mean a new browser trust-
// warning every time, unrelated to whether anything actually changed).
// This certificate's own trust has nothing to do with authenticating
// *callers* - that's the per-node CA check in dashboard/backend/
// internal/nodeproxy, and the admin password behind the main UI - it
// only establishes the encrypted channel.
//
// tlsCertFile/tlsKeyFile (from -tls-cert/-tls-key) let an operator
// supply a real certificate instead (a Let's Encrypt certificate, or
// one from an internal CA) - checked first, before ever touching
// dataDir; either both are set or neither is. Otherwise, a self-signed
// one (reusing internal/pki's own CA+Issue machinery rather than
// writing new crypto code here) is generated once and persisted to
// dataDir.
//
// extraAdvertiseAddresses (comma-separated, from -advertise-address)
// was added for Point 2 suite tranche 5: a self-registering node dials
// -register-addr directly (no browser involved), and Go's net/http
// client - unlike a browser - never lets an operator click through a
// hostname/SAN mismatch, so any deployment where this process can't see
// its own externally-reachable address on a local network interface
// (Docker bridge networking's host-side published port most commonly,
// but also a NAT/port-forwarded address) would otherwise refuse every
// self-registration attempt outright, even a genuinely legitimate one -
// found while building the node-side registration flow (internal/
// selfregister), not yet a reported real deployment failure, but the
// exact shape dashboard/README.md's own documented `docker run -p
// 8443:8443 ...` example produces. Only meaningful for the
// auto-generated identity - ignored entirely when a real certificate is
// supplied via -tls-cert/-tls-key, since that certificate's own SANs
// are the operator's responsibility.
func loadOrCreateDashboardIdentity(dataDir, extraAdvertiseAddresses, tlsCertFile, tlsKeyFile string) (tls.Certificate, error) {
	if tlsCertFile != "" || tlsKeyFile != "" {
		if tlsCertFile == "" || tlsKeyFile == "" {
			return tls.Certificate{}, fmt.Errorf("-tls-cert and -tls-key must both be set together")
		}
		return tls.LoadX509KeyPair(tlsCertFile, tlsKeyFile)
	}

	certPath := dataDir + "/dashboard-identity.crt"
	keyPath := dataDir + "/dashboard-identity.key"

	if certPEM, err := os.ReadFile(certPath); err == nil {
		keyPEM, err := os.ReadFile(keyPath)
		if err == nil {
			return tls.X509KeyPair(certPEM, keyPEM)
		}
	}

	ca, err := pki.NewCA("dashboard")
	if err != nil {
		return tls.Certificate{}, fmt.Errorf("generate dashboard identity: %w", err)
	}
	// App.jsx's openNode navigates to https://<window.location.hostname>:
	// <port>/ - whatever host the browser used to load the main SPA in
	// the first place (localhost most commonly, but not exclusively) -
	// so the SAN list needs to cover that, not just this process's own
	// view of itself. localhost/127.0.0.1/::1 are the guaranteed common
	// case; pki.LocalIPs() covers a real LAN address too, for a
	// --network host deployment or direct (non-Docker) local run - see
	// dashboard/README.md. A previous version issued this certificate
	// with zero SANs at all, which real modern TLS clients (browsers
	// included) reject outright regardless of CommonName.
	ips := append([]net.IP{net.ParseIP("127.0.0.1"), net.ParseIP("::1")}, pki.LocalIPs()...)
	dnsNames := []string{"localhost"}
	for _, entry := range strings.Split(extraAdvertiseAddresses, ",") {
		entry = strings.TrimSpace(entry)
		if entry == "" {
			continue
		}
		if ip := net.ParseIP(entry); ip != nil {
			ips = append(ips, ip)
		} else {
			dnsNames = append(dnsNames, entry)
		}
	}
	certPEM, keyPEM, err := ca.Issue(pki.IssueOptions{
		CommonName:  "dashboard",
		DNSNames:    dnsNames,
		IPAddresses: ips,
		ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	})
	if err != nil {
		return tls.Certificate{}, fmt.Errorf("issue dashboard server certificate: %w", err)
	}
	if err := os.WriteFile(certPath, certPEM, 0o600); err != nil {
		return tls.Certificate{}, fmt.Errorf("write %s: %w", certPath, err)
	}
	if err := os.WriteFile(keyPath, keyPEM, 0o600); err != nil {
		return tls.Certificate{}, fmt.Errorf("write %s: %w", keyPath, err)
	}
	return tls.X509KeyPair(certPEM, keyPEM)
}

// suggestRegisterAddress guesses the address a newly-provisioned node
// should be given as -controller-address (see cmd/janusctl's own
// lifecycle install flags) - the same host-selection logic
// loadOrCreateDashboardIdentity's SAN list already applies (prefer an
// explicitly configured -advertise-address, since this process can't
// reliably know its own externally-reachable address otherwise - see
// that function's own doc comment for why), paired with -register-addr's
// port. Best-effort only, and always presented as a suggestion the
// operator has to confirm for their actual network (handleControllerInfo
// returns it as-is, never silently substituted into anything that acts
// on it) - an empty result just means neither -advertise-address nor
// this host's own local interfaces yielded anything usable, not an
// error.
func suggestRegisterAddress(extraAdvertiseAddresses, registerAddr string) string {
	host := ""
	for _, entry := range strings.Split(extraAdvertiseAddresses, ",") {
		entry = strings.TrimSpace(entry)
		if entry != "" {
			host = entry
			break
		}
	}
	if host == "" {
		if ips := pki.LocalIPs(); len(ips) > 0 {
			host = ips[0].String()
		}
	}
	if host == "" {
		return ""
	}
	_, port, err := net.SplitHostPort(registerAddr)
	if err != nil || port == "" {
		return ""
	}
	return net.JoinHostPort(host, port)
}

// handleControllerInfo hands an operator everything needed to fill in
// `janusctl lifecycle install`'s -controller-address/-controller-ca
// flags for a new node - see docs/architecture.md's node self-
// registration design. The CA cert here is this dashboard's own TLS
// identity (the same one startRegistrationListener serves /register
// behind), not a separate credential - it's what a provisioned node
// verifies the Controller's identity against before ever sending it
// anything, matching InstallRequest's own "no trust-on-first-use" rule.
func (a *app) handleControllerInfo(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	caPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: a.serverCert.Certificate[0]})
	var fleetRoot []byte
	if a.fleet != nil {
		fleetRoot, _ = a.fleet.RootPEM()
	}
	writeJSON(w, http.StatusOK, struct {
		Address   string `json:"address"`
		CACertPEM string `json:"ca_cert_pem"`
		// FleetRootPEM is what a node of this release on is better
		// provisioned with: it checks the Controller through the fleet,
		// whatever certificate the Controller serves meanwhile.
		FleetRootPEM string `json:"fleet_root_pem,omitempty"`
		// Fingerprint is the SHA-256 of the certificate this port serves
		// - what janusctl login -controller-fingerprint checks.
		Fingerprint string `json:"fingerprint"`
	}{Address: a.suggestedRegisterAddr, CACertPEM: string(caPEM), FleetRootPEM: string(fleetRoot), Fingerprint: a.servedFingerprint()})
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

// envOr is flag.String's default value read from an environment
// variable first, if set - lets a couple of the more commonly-tuned
// flags (see their own help text) also be set via a Docker Compose
// environment: entry, which is more natural there than overriding the
// container's command just to change one value. A flag explicitly
// given on the command line still wins over the env var, same as any
// flag overriding its own stated default.
func envOr(key, fallback string) string {
	if v, ok := os.LookupEnv(key); ok {
		return v
	}
	return fallback
}
