// Command dashboardd is the management dashboard's backend - see the
// rebranding/dashboard/client-native plan for the full architecture.
// Serves the SPA + a REST/JSON API for managing the node registry on one
// HTTPS-only port (behind a single admin password - see internal/auth -
// forced setup on first run, session-cookie-gated after that; the
// session cookie is marked Secure, so this transport guarantee actually
// matters, not just cosmetic), and one dedicated HTTPS listener per
// registered node (see dashboard/backend/internal/nodeproxy) requiring a
// TLS client certificate signed by that node's own CA - a browser
// already holding a valid client cert for that node gets prompted to
// select it the first time it connects to that node's own port.
//
// Every TLS surface this process serves (the main UI, node self-
// registration, and every per-node listener) shares one identity
// certificate - see loadOrCreateDashboardIdentity: self-signed and
// auto-generated on first run by default (persisted to -data-dir, so
// it's stable across restarts - a fresh one every restart would mean a
// new browser trust warning every time for no reason), or -tls-cert/
// -tls-key to supply a real one instead (e.g. a Let's Encrypt
// certificate, or an internal CA's). Either way it's self-signed or
// otherwise not in a browser's default trust store, so a first visit to
// the main UI needs the same one-time click-through a per-node view
// already needed.
package main

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"embed"
	"encoding/json"
	"encoding/pem"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"log"
	"net"
	"net/http"
	"os"
	"strings"
	"sync"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	pkcs12 "software.sslmate.com/src/go-pkcs12"

	janusv1alpha1 "github.com/swenske/Janus/gen/janus/v1alpha1"
	"github.com/swenske/Janus/internal/pki"

	"github.com/swenske/Janus/dashboard/backend/internal/auth"
	"github.com/swenske/Janus/dashboard/backend/internal/nodeproxy"
	"github.com/swenske/Janus/dashboard/backend/internal/pending"
	"github.com/swenske/Janus/dashboard/backend/internal/store"
)

// staticFiles is dashboard/frontend's built React SPA - dashboard/
// backend/static, generated by `make dashboard-frontend-build`
// (dashboard/frontend's own `npm run build`, configured to output
// straight here - see vite.config.js). Committed to the repo the same
// way gen/janus/v1alpha1 is: never hand-edited, but committed
// anyway so a plain `go build ./...` never needs a Node.js toolchain
// just to compile - go:embed needs real files present at build time,
// not just at dashboard-image-build time.
//
//go:embed all:static
var staticFiles embed.FS

// portRangeStart/End: the pool of per-node listener ports - see the
// rebranding/dashboard plan's own architecture section for why a
// dynamic per-node port (not one shared port) is what makes native
// browser client-certificate selection work per node at all. This is
// exactly why the container needs --network host in practice, not just
// a wide -p range - see dashboard/README.md.
const (
	portRangeStart = 9500
	portRangeEnd   = 9599
)

func main() {
	addr := flag.String("addr", envOr("JANUS_CONTROLLER_ADDR", ":8080"), "main HTTPS address (node list, add/remove - never a credential) - e.g. \":443\" to run the UI on the standard HTTPS port; also settable via JANUS_CONTROLLER_ADDR (same \":port\"/\"host:port\" format - a flag takes precedence over the env var if both are given), for Docker Compose deployments where an environment: entry is more natural than overriding the container's command")
	registerAddr := flag.String("register-addr", ":8443", "TLS address nodes self-register against (see internal/pending) - not the same port pool as approved nodes' own per-node listeners")
	dataDir := flag.String("data-dir", "/data", "persistent data directory (Docker volume) - node registry + this dashboard's own TLS identity")
	advertiseAddresses := flag.String("advertise-address", envOr("JANUS_CONTROLLER_ADVERTISE_ADDRESS", ""), "comma-separated extra IPs/hostnames to add to this dashboard's TLS identity certificate, alongside loopback and this host's own local IPs (see loadOrCreateDashboardIdentity) - needed whenever a node or browser reaches -addr/-register-addr/the per-node ports through an address this process can't see on its own network interfaces (Docker bridge networking's host-side published port, a NAT/port-forwarded address, ...); only used the first time the identity is generated (or ignored entirely if -tls-cert/-tls-key are set), since it's cached to -data-dir afterward - delete <data-dir>/dashboard-identity.{crt,key} to regenerate after changing this; also settable via JANUS_CONTROLLER_ADVERTISE_ADDRESS, same reasoning as JANUS_CONTROLLER_ADDR above")
	tlsCertFile := flag.String("tls-cert", "", "path to a PEM certificate for this dashboard's own TLS identity (used for -addr, -register-addr, and every per-node listener) - if set, together with -tls-key, replaces the auto-generated self-signed one entirely; both flags must be set together")
	tlsKeyFile := flag.String("tls-key", "", "path to the PEM private key matching -tls-cert")
	flag.Parse()

	st, err := store.Open(*dataDir)
	if err != nil {
		log.Fatalf("open store: %v", err)
	}

	pendingStore, err := pending.Open(*dataDir)
	if err != nil {
		log.Fatalf("open pending store: %v", err)
	}

	authStore, err := auth.Open(*dataDir)
	if err != nil {
		log.Fatalf("open auth store: %v", err)
	}
	if authStore.SetupRequired() {
		log.Printf("no admin password set yet - the UI will force a one-time setup screen on first visit")
	}

	serverCert, err := loadOrCreateDashboardIdentity(*dataDir, *advertiseAddresses, *tlsCertFile, *tlsKeyFile)
	if err != nil {
		log.Fatalf("dashboard TLS identity: %v", err)
	}

	app := &app{
		store:                 st,
		pending:               pendingStore,
		auth:                  authStore,
		loginLimiter:          auth.NewLoginLimiter(),
		serverCert:            serverCert,
		listeners:             map[string]*nodeproxy.Listener{},
		suggestedRegisterAddr: suggestRegisterAddress(*advertiseAddresses, *registerAddr),
	}
	for _, n := range st.List() {
		if err := app.startListener(n); err != nil {
			// A node whose listener fails to start (e.g. its port is
			// somehow already taken) stays registered but unreachable -
			// logged, not fatal, so one bad node doesn't take the whole
			// dashboard down on restart.
			log.Printf("node %s (%s): start listener: %v", n.ID, n.Name, err)
		}
	}

	if err := app.startRegistrationListener(*registerAddr); err != nil {
		log.Fatalf("registration listener: %v", err)
	}

	spa, err := fs.Sub(staticFiles, "static")
	if err != nil {
		log.Fatalf("static assets: %v", err)
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/api/auth/status", app.handleAuthStatus)
	mux.HandleFunc("/api/auth/setup", app.handleAuthSetup)
	mux.HandleFunc("/api/auth/login", app.handleAuthLogin)
	mux.HandleFunc("/api/auth/logout", app.handleAuthLogout)
	mux.HandleFunc("/api/nodes", app.requireAuth(app.handleNodes))
	mux.HandleFunc("GET /api/nodes/status", app.requireAuth(app.handleNodesStatus))
	mux.HandleFunc("/api/nodes/", app.requireAuth(app.handleNode))
	mux.HandleFunc("/api/pending", app.requireAuth(app.handlePendingList))
	mux.HandleFunc("/api/pending/", app.requireAuth(app.handlePendingAction))
	mux.HandleFunc("/api/controller-info", app.requireAuth(app.handleControllerInfo))
	mux.Handle("/", http.FileServerFS(spa))

	srv := &http.Server{
		Addr: *addr,
		// The session cookie's SameSite=Strict already keeps it off
		// cross-site requests, but not off same-site ones (another port
		// or subdomain of the same host) - refuse any non-safe request
		// from another origin outright, the same protection every
		// per-node listener has (see nodeproxy.newHandler).
		Handler:   http.NewCrossOriginProtection().Handler(mux),
		TLSConfig: &tls.Config{Certificates: []tls.Certificate{serverCert}},
	}
	log.Printf("dashboardd listening on %s (HTTPS only)", *addr)
	// Empty cert/key file arguments: srv.TLSConfig.Certificates above is
	// what's actually used - ListenAndServeTLS falls back to it exactly
	// for this case (see its own doc comment).
	log.Fatal(srv.ListenAndServeTLS("", ""))
}

type app struct {
	store        *store.Store
	pending      *pending.Store
	auth         *auth.Store
	loginLimiter *auth.LoginLimiter
	serverCert   tls.Certificate
	// suggestedRegisterAddr is handleControllerInfo's best guess at the
	// address a node should be given as -controller-address at
	// provisioning time - see suggestRegisterAddress's own doc comment.
	// Empty when nothing suitable could be determined; the UI/operator
	// still has to confirm or override it for their actual network
	// either way, this is a convenience default, never authoritative.
	suggestedRegisterAddr string

	mu        sync.Mutex
	listeners map[string]*nodeproxy.Listener
}

func (a *app) startListener(n *store.Node) error {
	l, err := nodeproxy.Start(n, a.serverCert, a.store)
	if err != nil {
		return err
	}
	a.mu.Lock()
	a.listeners[n.ID] = l
	a.mu.Unlock()
	return nil
}

// addNodeRequest is the JSON form of "add a node": three raw PEM blocks
// pasted in directly. Superseded in the frontend by a .pfx upload (see
// parseAddNodeRequest below) - copying three separate PEM blocks by
// hand turned out to be real friction for one single one-time event,
// the same lesson cmd/janusd/main.go's own bootstrap print already
// learned (see its own comment on why the CA cert prints alongside the
// admin cert/key rather than being split across two recovery paths).
// Kept working, not just left for compatibility: hack/
// qemu-dashboard-test.sh drives this JSON path directly, and a script/
// CI caller with raw PEM files in hand (e.g. straight out of
// janusctl pki generate-client-config) has no reason to wrap them
// in a PKCS#12 file first just to satisfy the UI's preferred format.
type addNodeRequest struct {
	Name             string `json:"name"`
	Address          string `json:"address"`
	CACertPEM        string `json:"ca_cert_pem"`
	BootstrapCertPEM string `json:"bootstrap_cert_pem"`
	BootstrapKeyPEM  string `json:"bootstrap_key_pem"`
}

// parseAddNodeRequest reads name/address/CA-cert/bootstrap-cert/
// bootstrap-key from either a multipart/form-data upload (fields
// "name", "address", "pfx" file, "pfx_password" - the default the
// frontend now uses: a single .pfx file, no PEM text to paste at all)
// or the older addNodeRequest JSON body, dispatched on Content-Type.
// Both arrive at exactly the same three PEM blocks handleAddNode
// already knew what to do with - this function's only job is getting
// there from either shape.
func parseAddNodeRequest(r *http.Request) (name, address string, caPEM, certPEM, keyPEM []byte, err error) {
	if strings.HasPrefix(r.Header.Get("Content-Type"), "multipart/form-data") {
		// 1 MiB is generous for a .pfx holding one EC key + two small
		// certs (a few KB in practice) - just a sanity cap, not a real
		// constraint.
		if err := r.ParseMultipartForm(1 << 20); err != nil {
			return "", "", nil, nil, nil, fmt.Errorf("parse form: %w", err)
		}
		name = r.FormValue("name")
		address = r.FormValue("address")
		password := r.FormValue("pfx_password")

		file, _, ferr := r.FormFile("pfx")
		if ferr != nil {
			return "", "", nil, nil, nil, fmt.Errorf("read pfx upload: %w", ferr)
		}
		defer file.Close()
		pfxData, rerr := io.ReadAll(file)
		if rerr != nil {
			return "", "", nil, nil, nil, fmt.Errorf("read pfx upload: %w", rerr)
		}

		key, cert, caCerts, derr := pkcs12.DecodeChain(pfxData, password)
		if derr != nil {
			return "", "", nil, nil, nil, fmt.Errorf("decode pfx (wrong password?): %w", derr)
		}
		if len(caCerts) == 0 {
			return "", "", nil, nil, nil, fmt.Errorf("pfx has no CA certificate bundled - it needs to include the node's ca.crt (e.g. openssl pkcs12 -export -certfile ca.crt ...)")
		}
		keyDER, merr := x509.MarshalPKCS8PrivateKey(key)
		if merr != nil {
			return "", "", nil, nil, nil, fmt.Errorf("marshal private key from pfx: %w", merr)
		}
		certPEM = pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: cert.Raw})
		keyPEM = pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: keyDER})
		caPEM = pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: caCerts[0].Raw})
		return name, address, caPEM, certPEM, keyPEM, nil
	}

	var req addNodeRequest
	if derr := json.NewDecoder(r.Body).Decode(&req); derr != nil {
		return "", "", nil, nil, nil, fmt.Errorf("decode request: %w", derr)
	}
	return req.Name, req.Address, []byte(req.CACertPEM), []byte(req.BootstrapCertPEM), []byte(req.BootstrapKeyPEM), nil
}

func (a *app) handleNodes(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		type nodeView struct {
			ID      string `json:"id"`
			Name    string `json:"name"`
			Address string `json:"address"`
			Port    int    `json:"port"`
		}
		var out []nodeView
		for _, n := range a.store.List() {
			out = append(out, nodeView{ID: n.ID, Name: n.Name, Address: n.Addr(), Port: n.Port})
		}
		writeJSON(w, http.StatusOK, out)

	case http.MethodPost:
		a.handleAddNode(w, r)

	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

func (a *app) handleAddNode(w http.ResponseWriter, r *http.Request) {
	name, address, caPEM, bootstrapCertPEM, bootstrapKeyPEM, err := parseAddNodeRequest(r)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if name == "" || address == "" {
		http.Error(w, "name and address are required", http.StatusBadRequest)
		return
	}

	tlsConfig, err := pki.ClientTLSConfig(caPEM, bootstrapCertPEM, bootstrapKeyPEM)
	if err != nil {
		http.Error(w, fmt.Sprintf("build TLS config from provided credentials: %v", err), http.StatusBadRequest)
		return
	}
	conn, err := grpc.NewClient(address, grpc.WithTransportCredentials(credentials.NewTLS(tlsConfig)))
	if err != nil {
		http.Error(w, fmt.Sprintf("dial %s: %v", address, err), http.StatusBadGateway)
		return
	}
	defer conn.Close()

	ctx, cancel := context.WithTimeout(r.Context(), 10*time.Second)
	defer cancel()
	cfg, err := janusv1alpha1.NewSystemServiceClient(conn).GenerateClientConfiguration(ctx, &janusv1alpha1.GenerateClientConfigurationRequest{
		Roles: []string{pki.RoleAdmin},
	})
	if err != nil {
		http.Error(w, fmt.Sprintf("GenerateClientConfiguration against %s: %v - the provided bootstrap credential couldn't reach or authenticate to that node", address, err), http.StatusBadGateway)
		return
	}
	// bootstrapCertPEM/bootstrapKeyPEM are never referenced again past
	// this point - only cfg's freshly-issued service credential is
	// persisted below.

	port, err := a.allocatePort()
	if err != nil {
		http.Error(w, err.Error(), http.StatusInsufficientStorage)
		return
	}

	node := &store.Node{
		Name:           name,
		Address:        address,
		Port:           port,
		CACertPEM:      cfg.GetCa(),
		ServiceCertPEM: cfg.GetCrt(),
		ServiceKeyPEM:  cfg.GetKey(),
	}
	if err := a.store.Add(node); err != nil {
		http.Error(w, fmt.Sprintf("persist node: %v", err), http.StatusInternalServerError)
		return
	}
	if err := a.startListener(node); err != nil {
		http.Error(w, fmt.Sprintf("node registered but its listener failed to start: %v", err), http.StatusInternalServerError)
		return
	}

	writeJSON(w, http.StatusCreated, struct {
		ID   string `json:"id"`
		Port int    `json:"port"`
	}{ID: node.ID, Port: node.Port})
}

func (a *app) handleNode(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodDelete {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	id := r.URL.Path[len("/api/nodes/"):]
	if id == "" {
		http.Error(w, "missing node id", http.StatusBadRequest)
		return
	}

	a.mu.Lock()
	l, ok := a.listeners[id]
	delete(a.listeners, id)
	a.mu.Unlock()
	if ok {
		ctx, cancel := context.WithTimeout(r.Context(), 5*time.Second)
		defer cancel()
		if err := l.Stop(ctx); err != nil {
			log.Printf("node %s: stop listener: %v", id, err)
		}
	}

	if err := a.store.Remove(id); err != nil {
		http.Error(w, err.Error(), http.StatusNotFound)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// allocatePort returns the first port in [portRangeStart, portRangeEnd]
// not already used by a registered node - not concurrency-safe against
// two simultaneous add-node requests racing for the same port (fine for
// a first slice: this dashboard is a single operator's own tool, not a
// multi-tenant service).
// handleNodesStatus reports every registered node's live status, queried
// concurrently with a short timeout so one unreachable node can't stall
// the node list.
func (a *app) handleNodesStatus(w http.ResponseWriter, r *http.Request) {
	nodes := a.store.List()
	out := make(map[string]nodeproxy.NodeStatus, len(nodes))
	var mu sync.Mutex
	var wg sync.WaitGroup
	for _, n := range nodes {
		wg.Add(1)
		go func() {
			defer wg.Done()
			ctx, cancel := context.WithTimeout(r.Context(), 4*time.Second)
			defer cancel()
			st := nodeproxy.Status(ctx, n)
			mu.Lock()
			out[n.ID] = st
			mu.Unlock()
		}()
	}
	wg.Wait()
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(out)
}

func (a *app) allocatePort() (int, error) {
	used := a.store.UsedPorts()
	for p := portRangeStart; p <= portRangeEnd; p++ {
		if !used[p] {
			return p, nil
		}
	}
	return 0, fmt.Errorf("no free port in [%d, %d] - %d nodes already registered", portRangeStart, portRangeEnd, len(used))
}

// loadOrCreateDashboardIdentity gives every TLS surface this process
// serves (the main UI, node self-registration, and every per-node
// listener) one stable server certificate across restarts (a fresh
// self-signed identity every restart would mean a new browser trust-
// warning every time, unrelated to whether anything actually changed).
// This certificate's own trust has nothing to do with authenticating
// *callers* - that's the per-node CA check in dashboard/backend/
// internal/nodeproxy, and the admin password behind the main UI - it
// only establishes the encrypted channel.
//
// tlsCertFile/tlsKeyFile (from -tls-cert/-tls-key) let an operator
// supply a real certificate instead (a Let's Encrypt certificate, or
// one from an internal CA) - checked first, before ever touching
// dataDir; either both are set or neither is. Otherwise, a self-signed
// one (reusing internal/pki's own CA+Issue machinery rather than
// writing new crypto code here) is generated once and persisted to
// dataDir.
//
// extraAdvertiseAddresses (comma-separated, from -advertise-address)
// was added for Point 2 suite tranche 5: a self-registering node dials
// -register-addr directly (no browser involved), and Go's net/http
// client - unlike a browser - never lets an operator click through a
// hostname/SAN mismatch, so any deployment where this process can't see
// its own externally-reachable address on a local network interface
// (Docker bridge networking's host-side published port most commonly,
// but also a NAT/port-forwarded address) would otherwise refuse every
// self-registration attempt outright, even a genuinely legitimate one -
// found while building the node-side registration flow (internal/
// selfregister), not yet a reported real deployment failure, but the
// exact shape dashboard/README.md's own documented `docker run -p
// 8443:8443 ...` example produces. Only meaningful for the
// auto-generated identity - ignored entirely when a real certificate is
// supplied via -tls-cert/-tls-key, since that certificate's own SANs
// are the operator's responsibility.
func loadOrCreateDashboardIdentity(dataDir, extraAdvertiseAddresses, tlsCertFile, tlsKeyFile string) (tls.Certificate, error) {
	if tlsCertFile != "" || tlsKeyFile != "" {
		if tlsCertFile == "" || tlsKeyFile == "" {
			return tls.Certificate{}, fmt.Errorf("-tls-cert and -tls-key must both be set together")
		}
		return tls.LoadX509KeyPair(tlsCertFile, tlsKeyFile)
	}

	certPath := dataDir + "/dashboard-identity.crt"
	keyPath := dataDir + "/dashboard-identity.key"

	if certPEM, err := os.ReadFile(certPath); err == nil {
		keyPEM, err := os.ReadFile(keyPath)
		if err == nil {
			return tls.X509KeyPair(certPEM, keyPEM)
		}
	}

	ca, err := pki.NewCA("dashboard")
	if err != nil {
		return tls.Certificate{}, fmt.Errorf("generate dashboard identity: %w", err)
	}
	// App.jsx's openNode navigates to https://<window.location.hostname>:
	// <port>/ - whatever host the browser used to load the main SPA in
	// the first place (localhost most commonly, but not exclusively) -
	// so the SAN list needs to cover that, not just this process's own
	// view of itself. localhost/127.0.0.1/::1 are the guaranteed common
	// case; pki.LocalIPs() covers a real LAN address too, for a
	// --network host deployment or direct (non-Docker) local run - see
	// dashboard/README.md. A previous version issued this certificate
	// with zero SANs at all, which real modern TLS clients (browsers
	// included) reject outright regardless of CommonName.
	ips := append([]net.IP{net.ParseIP("127.0.0.1"), net.ParseIP("::1")}, pki.LocalIPs()...)
	dnsNames := []string{"localhost"}
	for _, entry := range strings.Split(extraAdvertiseAddresses, ",") {
		entry = strings.TrimSpace(entry)
		if entry == "" {
			continue
		}
		if ip := net.ParseIP(entry); ip != nil {
			ips = append(ips, ip)
		} else {
			dnsNames = append(dnsNames, entry)
		}
	}
	certPEM, keyPEM, err := ca.Issue(pki.IssueOptions{
		CommonName:  "dashboard",
		DNSNames:    dnsNames,
		IPAddresses: ips,
		ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	})
	if err != nil {
		return tls.Certificate{}, fmt.Errorf("issue dashboard server certificate: %w", err)
	}
	if err := os.WriteFile(certPath, certPEM, 0o600); err != nil {
		return tls.Certificate{}, fmt.Errorf("write %s: %w", certPath, err)
	}
	if err := os.WriteFile(keyPath, keyPEM, 0o600); err != nil {
		return tls.Certificate{}, fmt.Errorf("write %s: %w", keyPath, err)
	}
	return tls.X509KeyPair(certPEM, keyPEM)
}

// suggestRegisterAddress guesses the address a newly-provisioned node
// should be given as -controller-address (see cmd/janusctl's own
// lifecycle install flags) - the same host-selection logic
// loadOrCreateDashboardIdentity's SAN list already applies (prefer an
// explicitly configured -advertise-address, since this process can't
// reliably know its own externally-reachable address otherwise - see
// that function's own doc comment for why), paired with -register-addr's
// port. Best-effort only, and always presented as a suggestion the
// operator has to confirm for their actual network (handleControllerInfo
// returns it as-is, never silently substituted into anything that acts
// on it) - an empty result just means neither -advertise-address nor
// this host's own local interfaces yielded anything usable, not an
// error.
func suggestRegisterAddress(extraAdvertiseAddresses, registerAddr string) string {
	host := ""
	for _, entry := range strings.Split(extraAdvertiseAddresses, ",") {
		entry = strings.TrimSpace(entry)
		if entry != "" {
			host = entry
			break
		}
	}
	if host == "" {
		if ips := pki.LocalIPs(); len(ips) > 0 {
			host = ips[0].String()
		}
	}
	if host == "" {
		return ""
	}
	_, port, err := net.SplitHostPort(registerAddr)
	if err != nil || port == "" {
		return ""
	}
	return net.JoinHostPort(host, port)
}

// handleControllerInfo hands an operator everything needed to fill in
// `janusctl lifecycle install`'s -controller-address/-controller-ca
// flags for a new node - see docs/architecture.md's node self-
// registration design. The CA cert here is this dashboard's own TLS
// identity (the same one startRegistrationListener serves /register
// behind), not a separate credential - it's what a provisioned node
// verifies the Controller's identity against before ever sending it
// anything, matching InstallRequest's own "no trust-on-first-use" rule.
func (a *app) handleControllerInfo(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	caPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: a.serverCert.Certificate[0]})
	writeJSON(w, http.StatusOK, struct {
		Address   string `json:"address"`
		CACertPEM string `json:"ca_cert_pem"`
	}{Address: a.suggestedRegisterAddr, CACertPEM: string(caPEM)})
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

// envOr is flag.String's default value read from an environment
// variable first, if set - lets a couple of the more commonly-tuned
// flags (see their own help text) also be set via a Docker Compose
// environment: entry, which is more natural there than overriding the
// container's command just to change one value. A flag explicitly
// given on the command line still wins over the env var, same as any
// flag overriding its own stated default.
func envOr(key, fallback string) string {
	if v, ok := os.LookupEnv(key); ok {
		return v
	}
	return fallback
}
